import React, { useState } from 'react';

export default function RecommendationsReview() {
  const [recommendations, setRecommendations] = useState([
    {
      title: 'Increase Recycled Material Usage',
      basis: 'Current secondary aluminum input (34%) is lower than simulated optimal threshold (45%).',
      expectedImprovement: 'Lower overall carbon impact by ~12% per ton.',
      status: 'Accepted',
      note: 'Verified with scrap supply contract.'
    },
    {
      title: 'Consider Lower-Impact Transportation',
      basis: 'Heavy-duty trucking on Route Bux-09 contributes disproportionately high Scope 3 emissions.',
      expectedImprovement: 'Shift 60% of bauxite transport to rail (-2.4 kt CO2e/yr).',
      status: 'Accepted',
      note: 'Rail spur capacity confirmed.'
    },
    {
      title: 'Improve Material Recovery',
      basis: 'Material loss detected in dross processing phase at Facility C.',
      expectedImprovement: 'Closed-loop dross pressing (+8 circularity points).',
      status: 'Pending',
      note: 'Awaiting equipment spec sheet.'
    }
  ]);

  const toggleStatus = (index, newStatus) => {
    setRecommendations((prev) =>
      prev.map((rec, i) => (i === index ? { ...rec, status: newStatus } : rec))
    );
  };

  return (
    <div className="max-w-7xl mx-auto space-y-gutter">
      <header className="mb-xl">
        <h2 className="font-headline-lg text-headline-lg text-on-surface font-bold tracking-tight mb-sm">
          Recommendations Review
        </h2>
        <p className="font-body-md text-body-md text-on-surface-variant">
          Audit review &amp; verification of decarbonization mitigation steps generated by EcoMetrix AI.
        </p>
      </header>

      <div className="space-y-md">
        {recommendations.map((rec, i) => (
          <div key={i} className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm space-y-md">
            <div className="flex justify-between items-start">
              <div>
                <span className="font-label-md text-[10px] text-tertiary font-bold uppercase tracking-wider">
                  Recommendation #{i + 1}
                </span>
                <h3 className="font-bold text-base text-on-surface mt-0.5">{rec.title}</h3>
              </div>
              <span
                className={`px-2.5 py-1 rounded text-xs font-bold ${
                  rec.status === 'Accepted'
                    ? 'bg-primary-container/20 text-primary'
                    : rec.status === 'Flagged'
                    ? 'bg-error-container text-error'
                    : 'bg-amber-100 text-amber-800'
                }`}
              >
                {rec.status === 'Accepted' ? '✓ Accepted' : rec.status === 'Flagged' ? '⚠ Flagged' : '⌛ Pending Review'}
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-md text-xs bg-surface-bright p-md rounded-lg border border-outline-variant">
              <div>
                <span className="font-bold text-on-surface block mb-1">Analytical Basis:</span>
                <p className="text-on-surface-variant">{rec.basis}</p>
              </div>
              <div>
                <span className="font-bold text-on-surface block mb-1">Expected Improvement:</span>
                <p className="text-primary font-semibold">{rec.expectedImprovement}</p>
              </div>
            </div>

            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-3 pt-2 text-xs">
              <span className="text-on-surface-variant italic">Audit Note: {rec.note}</span>

              <div className="flex gap-2">
                <button
                  onClick={() => toggleStatus(i, 'Accepted')}
                  className="bg-primary text-on-primary px-3 py-1.5 rounded font-bold hover:bg-primary-fixed-variant transition-colors cursor-pointer"
                >
                  Accept
                </button>
                <button
                  onClick={() => toggleStatus(i, 'Flagged')}
                  className="bg-surface-bright border border-outline-variant text-error hover:bg-error-container px-3 py-1.5 rounded font-bold transition-colors cursor-pointer"
                >
                  Flag
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
